// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture

//One element for each agent
RWStructuredBuffer<float3> agentsPos; 
RWStructuredBuffer<float3> agentsVelocity;

RWStructuredBuffer<float3> resultVelocity; //This is what we'll be returning


[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!

}
